import React from 'react'
import Image from 'next/image'
import Link from 'next/link'
import { ArrowLeft } from 'lucide-react'
import Footer from "@/app/components/Footer"

const page = () => {
  return (
    <>
      <div className="max-w-[1200px] mx-auto px-4 pt-8">
        <div className="grid grid-cols-3 items-center">
          <div className="justify-self-start">
            <Link href="/" className="inline-flex items-center gap-2 text-sm hover:underline">
              <ArrowLeft size={16} />
              <span>Back</span>
            </Link>
          </div>
          <div className="justify-self-center">
            <div className="flex items-center gap-3">
              <Image src="/logo.png" alt="Firm logo" width={36} height={36} />
              <span className="text-sm font-semibold tracking-wide">P.A. ISOH LEGAL <br/> CONSULTANTS</span>
            </div>
          </div>
          <div className="justify-self-end" />
        </div>
      </div>

      <main className="max-w-[900px] mx-auto px-4 py-16">
        <h1 className="mb-2">Privacy Policy</h1>
        <p className="text-sm text-[#4b4b4b] mb-8">Last updated: October 09, 2025</p>

        <p className="mb-6">
          This Privacy Policy describes Our policies and procedures on the collection, use and
          disclosure of Your information when You use the Service and tells You about Your privacy
          rights and how the law protects You. We use Your Personal data to provide and improve the
          Service. By using the Service, You agree to the collection and use of information in accordance
          with this Privacy Policy. This Privacy Policy has been created with the help of the Privacy Policy Generator.
        </p>

        <h2 className="mb-3">Interpretation and Definitions</h2>
        <h3 className="mb-2">Interpretation</h3>
        <p className="mb-6">
          The words whose initial letters are capitalized have meanings defined under the following
          conditions. The following definitions shall have the same meaning regardless of whether
          they appear in singular or in plural.
        </p>

        <h3 className="mb-2">Definitions</h3>
        <p className="mb-3">For the purposes of this Privacy Policy:</p>
        <ul className="list-disc pl-6 space-y-2 mb-8">
          <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
          <li><strong>Affiliate</strong> means an entity that controls, is controlled by, or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to P. A. Isoh Legal Consultants, Kingfem Plaza, Mabushi, FCT, Abuja.</li>
          <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
          <li><strong>Country</strong> refers to: Nigeria</li>
          <li><strong>Device</strong> means any device that can access the Service such as a computer, a cell phone or a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company. It refers to third-party companies or individuals employed by the Company to facilitate the Service, to provide the Service on behalf of the Company, to perform services related to the Service or to assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to P. A. Isoh Legal Consultants, accessible from <a className="underline" href="https://www.isohlegal.com" target="_blank" rel="noopener noreferrer">https://www.isohlegal.com</a></li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h2 className="mb-3">Collecting and Using Your Personal Data</h2>
        <h3 className="mb-2">Types of Data Collected</h3>
        <h4 className="mb-2 font-semibold">Personal Data</h4>
        <p className="mb-3">While using Our Service, We may ask You to provide Us with certain personally identifiable information that can be used to contact or identify You. Personally identifiable information may include, but is not limited to:</p>
        <ul className="list-disc pl-6 space-y-1 mb-6">
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Address, State, Province, ZIP/Postal code, City</li>
          <li>Usage Data</li>
        </ul>

        <h4 className="mb-2 font-semibold">Usage Data</h4>
        <p className="mb-6">
          Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device's unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data. We may also collect information that Your browser sends whenever You visit Our Service or when You access the Service by or through a mobile device.
        </p>

        <h3 className="mb-2">Tracking Technologies and Cookies</h3>
        <p className="mb-3">We use Cookies and similar tracking technologies to track the activity on Our Service and store certain information. Tracking technologies We use include beacons, tags, and scripts to collect and track information and to improve and analyze Our Service. The technologies We use may include:</p>
        <ul className="list-disc pl-6 space-y-2 mb-3">
          <li><strong>Cookies or Browser Cookies.</strong> A cookie is a small file placed on Your Device. You can instruct Your browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser setting so that it will refuse Cookies, our Service may use Cookies.</li>
          <li><strong>Web Beacons.</strong> Certain sections of our Service and our emails may contain small electronic files known as web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for example, to count users who have visited those pages or opened an email and for other related website statistics (for example, recording the popularity of a certain section and verifying system and server integrity).</li>
        </ul>
        <p className="mb-6">Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web browser. We use both Session and Persistent Cookies for the purposes set out below:</p>
        <ul className="list-disc pl-6 space-y-2 mb-6">
          <li><strong>Necessary / Essential Cookies</strong> (Session; administered by Us): These Cookies are essential to provide You with services available through the Website and to enable You to use some of its features. They help to authenticate users and prevent fraudulent use of user accounts.</li>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong> (Persistent; administered by Us): These Cookies identify if users have accepted the use of cookies on the Website.</li>
          <li><strong>Functionality Cookies</strong> (Persistent; administered by Us): These Cookies allow us to remember choices You make when You use the Website, such as remembering your login details or language preference.</li>
        </ul>
        <p className="mb-8">For more information about the cookies we use and your choices regarding cookies, please visit our Cookies Policy or the Cookies section of our Privacy Policy.</p>

        <h2 className="mb-3">Use of Your Personal Data</h2>
        <p className="mb-3">The Company may use Personal Data for the following purposes:</p>
        <ul className="list-disc pl-6 space-y-2 mb-6">
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage Your Account: to manage Your registration as a user of the Service.</li>
          <li>For the performance of a contract: development, compliance and undertaking of contracts.</li>
          <li>To contact You: via email, telephone, SMS, or other electronic communications.</li>
          <li>To provide You with news, special offers, and general information about goods and services similar to those already purchased or inquired about.</li>
          <li>To manage Your requests.</li>
          <li>For business transfers: evaluate or conduct a merger, divestiture, restructuring, or sale.</li>
          <li>For other purposes: data analysis, usage trends, promotional effectiveness, improving the Service.</li>
        </ul>

        <p className="mb-3">We may share Your personal information in the following situations:</p>
        <ul className="list-disc pl-6 space-y-2 mb-8">
          <li>With Service Providers</li>
          <li>For business transfers</li>
          <li>With Affiliates</li>
          <li>With business partners</li>
          <li>With other users</li>
          <li>With Your consent</li>
        </ul>

        <h2 className="mb-3">Retention of Your Personal Data</h2>
        <p className="mb-6">The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy, and as required to comply with legal obligations, resolve disputes, and enforce agreements.</p>

        <h2 className="mb-3">Transfer of Your Personal Data</h2>
        <p className="mb-8">Your information may be transferred to and maintained on computers located outside of Your jurisdiction where data protection laws may differ. We will take all reasonably necessary steps to ensure that Your data is treated securely and in accordance with this Privacy Policy.</p>

        <h2 className="mb-3">Delete Your Personal Data</h2>
        <p className="mb-8">You have the right to delete or request that We assist in deleting Personal Data We have collected about You. You may contact Us to request access to, correct, or delete any personal information that You have provided to Us, subject to legal obligations.</p>

        <h2 className="mb-3">Disclosure of Your Personal Data</h2>
        <h3 className="mb-2">Business Transactions</h3>
        <p className="mb-6">If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be transferred, with notice provided before becoming subject to a different Privacy Policy.</p>
        <h3 className="mb-2">Law enforcement</h3>
        <p className="mb-6">Under certain circumstances, the Company may be required to disclose Your Personal Data if required to do so by law or in response to valid requests by public authorities.</p>
        <h3 className="mb-2">Other legal requirements</h3>
        <ul className="list-disc pl-6 space-y-2 mb-8">
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of Users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h2 className="mb-3">Security of Your Personal Data</h2>
        <p className="mb-8">We strive to use commercially reasonable means to protect Your Personal Data, but no method of transmission over the Internet or electronic storage is 100% secure.</p>

        <h2 className="mb-3">Children's Privacy</h2>
        <p className="mb-8">Our Service does not address anyone under the age of 13, and we do not knowingly collect personally identifiable information from anyone under 13. If you believe a child has provided us with Personal Data, please contact us.</p>

        <h2 className="mb-3">Links to Other Websites</h2>
        <p className="mb-8">Our Service may contain links to other websites not operated by Us. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.</p>

        <h2 className="mb-3">Changes to this Privacy Policy</h2>
        <p className="mb-8">We may update Our Privacy Policy from time to time. We will notify You by posting the new Privacy Policy on this page and updating the "Last updated" date. You are advised to review this Privacy Policy periodically for any changes.</p>

        <h2 className="mb-3">Contact Us</h2>
        <p className="mb-3">If you have any questions about this Privacy Policy, You can contact us:</p>
        <ul className="list-disc pl-6 space-y-2">
          <li>By email: <a className="underline" href="mailto:Isohprecious99@gmail.com">Isohprecious99@gmail.com</a></li>
        </ul>
      </main>

      <Footer />
    </>
  )
}

export default page
